# Generated by Django 5.0.1 on 2024-01-03 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('fees', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('belt_color', models.CharField(choices=[('Colour Belt', 'Colour Belt'), ('Black Belt', 'Black Belt')], max_length=20)),
                ('weight', models.FloatField()),
                ('kata', models.BooleanField(default=False)),
                ('kumite', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.club')),
            ],
        ),
    ]
