# Generated by Django 5.0.1 on 2024-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_club_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='weight_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
