# Generated by Django 5.0.1 on 2024-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_candidate_weight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='entry_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
